services:
  users-database:
    image: 'postgres:15'
    environment:
      POSTGRES_DB: ${USERS_DATABASE_NAME}
      POSTGRES_USER: ${USERS_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${USERS_DATABASE_PASSWORD}
    ports:
      - "5432:5432"
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./apps/api-gateway/.env

  users-microservice:
    build:
      context: .
      dockerfile: ./apps/users-microservice/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - ./apps/users-microservice/.env
    depends_on:
      - users-database
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: raffinnaisse
      RABBITMQ_DEFAULT_PASS: raffinnaisse08
